sudo: required
services:
- docker
cache: false
jobs:
  include:
    - stage: before_install
      script: cd support/acceptance-testing
    - stage: install
      script: docker-compose build
    - stage: test
      script: docker-compose run acceptance gradle sauceChromeTests
    - script: docker-compose run acceptance gradle sauceFirefoxTests
    - script: docker-compose run acceptance gradle sauceIeTests
    - stage: before_deploy
      script: docker ps -a && docker cp `docker ps -aqf "name=_acceptance_"`:/home/groovy/acceptance/build/reports /tmp/
    - stage: deploy
      provider: pages
      skip_cleanup: true
      github_token: $GITHUB_TOKEN
      local_dir: /tmp/reports
      on:
        branch: master
