sudo: required
services:
- docker
before_install:
- docker pull qcifengineering/acceptance-testing
- cd support/acceptance-testing
- docker-compose rm -f
install:
- docker-compose build
script:
- docker-compose run acceptance gradle test
