sudo: required
services:
- docker
cache: false
before_install:
- cd support/acceptance-testing
install:
- docker-compose build
script:
- docker-compose run acceptance gradle sauceLabsCoreDevices
before_deploy:
- docker ps -a
- docker cp `docker ps -aqf "name=_acceptance_"`:/home/groovy/acceptance/build/reports /tmp/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: /tmp/reports
  on:
    branch: master
