version: '2'
services:
  dlcfportal:
    build: .
    image: qcifengineering/dlcf-portal:latest
    ports:
       - "1500:1500"
    volumes:
       - ".:/opt/rds-rdmp-portal"
    expose:
       - "1500"
    environment:
      - NODE_ENV=development
      - PORT=1500
      - sails_redbox__apiKey=c8e844fc-8550-497f-b970-7900ec8741ca
    links:
      - mongodb:mongodb
      - redbox:redbox
    entrypoint: /bin/bash -c "cd /opt/rds-rdmp-portal && node app.js"
  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - "./devdata:/devdata"
      - "/mnt/data/mongo/data/db:/data/db"
      - "/var/log/mongo:/var/log/mongo"
    ports:
       - "27017:27017"
  redbox:
    image: qcifengineering/dlcf-redbox
    environment:
      - RB_API_KEY=c8e844fc-8550-497f-b970-7900ec8741ca
      - RAID_URL=https://api.raid.org.au:8000/
      - RAID_KEY=f82ac16bec53a4418ffe8663fada204d1ba571c4
    volumes:
        - "/mnt/data/redbox:/opt/redbox/data"
        - "/var/log/redbox:/opt/redbox/home/logs"
    ports:
       - "9000:9000"
